version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis:/data
  hashgenerator:
    build:
      context: ./hashgenerator
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
  pastebin:
    build:
      context: ./pastebin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
