version: '3'
services:
  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - pastebin/.env
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis:/data
  hashgenerator:
    build:
      context: ./hashgenerator
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - redis
  pastebin:
    env_file:
      - pastebin/.env
    build:
      context: ./pastebin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"